# Generated by Django 5.1.6 on 2025-03-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, max_length=100, null=True)),
                ('server_1', models.CharField(blank=True, max_length=100, null=True)),
                ('server_2', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ipv4_address', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('dhcp_0', models.BooleanField(default=False)),
                ('ipv4_address_1', models.CharField(blank=True, max_length=100, null=True)),
                ('dhcp_1', models.BooleanField(default=False)),
                ('ntp_server', models.CharField(blank=True, max_length=100, null=True)),
                ('authentication_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
